### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by paulprocacci** [lix2ng/c3bt#1]
Line 422 of .c 

loc is on the stack.
While you can point to it via *cur, that stack disappears upon leave of function.
*cur therefore may point to something unexpected in future.

**Comment by lix2ng** [comment]
Wow, first report after almost 10 years! Glad to see it.
"cur" is an optional arg to output a cursor, and on line 445 *cur is updated with loc by value.
There is no "returning stack address" issue here.

As a side note, loc's values aren't fully initilized in all paths -- and this behavior fufills the specified "invalid/undefined" cases, e.g. in c3bt_locate().

**Comment by lix2ng** [comment]
Wow, first report after almost 10 years! Glad to see it.
"cur" is an optional arg to output a cursor, and on line 445 *cur is updated with loc by value.
There is no "returning stack address" issue here.

As a side note, loc's values aren't fully initilized in all paths -- and this behavior fufills the specified "invalid/undefined" cases, e.g. in c3bt_locate().

**Comment by paulprocacci** [comment]
You're actually right.  It isn't a bug.  Guess that what happens when you are up all night typing away.
